baseURL = 'https://drylabs.dev/'
languageCode = 'en-us'
title = 'Blog do Kuno'
theme = "hugoplate"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir need to be true if you want to use the language code as a subdirectory and language specific 404 page
defaultContentLanguageInSubdir = false

[params]
  github = 'https://github.com/Gustavmk'
  username = 'Gustavmk'
  [params.giscus]
    repo = 'gustavmk.github.io'
    repoId = 'R_kgDOKxFiSg'
    category = 'Blog'
    categoryId = 'DIC_kwDOKxFiSs4Conj3'
    mapping = 'path'
    reactionsEnabled = '1'
    inputPosition = 'bottom'
    theme = 'light'
    lang = 'en'

########################## Pagination ############################
[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

############################# Build ##############################
[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'

############################# Modules ############################
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################


############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]


########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true



############################# Plugins ##############################
